### ISSUE TITLE
Error running GPW - OpenNLP

### ISSUE THREAD

**Issue by joeferner** [lumifyio/lumify#471]
java.lang.NullPointerException: visibilityJson cannot be null
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:204)
        at io.lumify.core.model.termMention.TermMentionBuilder.save(TermMentionBuilder.java:159)
        at io.lumify.opennlpme.OpenNLPMaximumEntropyExtractorGraphPropertyWorker.createTermMention(OpenNLPMaximumEntropyExtractorGraphPropertyWorker.java:93)
        at io.lumify.opennlpme.OpenNLPMaximumEntropyExtractorGraphPropertyWorker.processLine(OpenNLPMaximumEntropyExtractorGraphPropertyWorker.java:79)
        at io.lumify.opennlpme.OpenNLPMaximumEntropyExtractorGraphPropertyWorker.execute(OpenNLPMaximumEntropyExtractorGraphPropertyWorker.java:62)
        at io.lumify.core.ingest.graphProperty.GraphPropertyThreadedWrapper.run(GraphPropertyThreadedWrapper.java:59)
        at java.lang.Thread.run(Thread.java:745)

**Comment by joeferner** [comment]
Closed see issue #475
