### ISSUE TITLE
unable to start jetty (container): LumifyException: Could not find relationship by intent: entityHasImage

### ISSUE THREAD

**Issue by mloepfe** [lumifyio/lumify#539]
With the newest version from git repo I'm not able to start jetty. I get the following exception:

com.google.inject.ProvisionException: Guice provision errors:||1) Error injecting constructor, io.lumify.core.exception.LumifyException: Could not find relationship by intent: entityHasImage|  at io.lumify.web.routes.workspace.WorkspaceHelper.<init>(WorkspaceHelper.java:51)|  at io.lumify.web.routes.workspace.WorkspaceHelper.class(WorkspaceHelper.java:31)|  while locating io.lumify.web.routes.workspace.WorkspaceHelper|    for parameter 1 at io.lumify.web.routes.vertex.VertexRemove.<init>(VertexRemove.java:34)|  while locating io.lumify.web.routes.vertex.VertexRemove||1 error
	at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:987)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1013)
	at io.lumify.web.WebApp.instantiateHandlers(WebApp.java:60)
...

io.lumify.core.exception.LumifyException: Could not find relationship by intent: entityHasImage
	at io.lumify.core.model.ontology.OntologyRepositoryBase.getRequiredRelationshipByIntent(OntologyRepositoryBase.java:875)
	at io.lumify.core.model.ontology.OntologyRepositoryBase.getRequiredRelationshipIRIByIntent(OntologyRepositoryBase.java:882)
	at io.lumify.web.routes.workspace.WorkspaceHelper.<init>(WorkspaceHelper.java:59)
	at io.lumify.web.routes.workspace.WorkspaceHelper$$FastClassByGuice$$95ee75ce.newInstance(<generated>)
...

**Comment by joeferner** [comment]
Fixed by commit 3659a46a61a662008a6f044886b78583fccdd9b6 and 899fec3a3dbc7dc83a4a189c0b069d6a4e6d973f

You may still get errors from graph property workers and long running processes but the web app should start and allow you upload an ontology.
