### ISSUE TITLE
http://lumify.io/wikipedia doesn't exist

### ISSUE THREAD

**Issue by smakolski** [lumifyio/lumify#624]
I'm trying to follow the readme for:

https://github.com/lumifyio/lumify/tree/master/datasets/wikipedia

and when I go to submit the MR job, I get:

```java
Exception in thread "main" java.lang.RuntimeException: http://lumify.io/wikipedia#wikipediaPage concept not found
        at io.lumify.wikipedia.mapreduce.ImportMR.verifyWikipediaPageConcept(ImportMR.java:57)
        at io.lumify.wikipedia.mapreduce.ImportMR.setupJob(ImportMR.java:31)
        at io.lumify.core.mapreduce.LumifyMRBase.run(LumifyMRBase.java:58)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
        at io.lumify.wikipedia.mapreduce.ImportMR.main(ImportMR.java:73)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:212)
```

Indeed, I can verify that http://lumify.io/wikipedia gives me a 404. Has this resource simply been moved or is it now removed entirely?

**Comment by mrburrito** [comment]
Follow the instructions [here](https://github.com/lumifyio/lumify/blob/master/docs/ontology.md) to import both the dev and wikipedia ontologies. The error you're seeing is because Lumify doesn't recognize the data types you are trying to import. We'll update the instructions page; that link is in the "Running from IDE" section below the MR instructions.
