### ISSUE TITLE
'vagrant up' fails due to too many open files

### ISSUE THREAD

**Issue by Joshfindit** [lumifyio/lumify#673]
after cloning the repository and `cd lumify`:

`vagrant up` continues until 

```
==> demo: [INFO]
==> demo: [INFO] ------------------------------------------------------------------------
==> demo: [INFO] Building Lumify: Web: Base 0.5.0-SNAPSHOT
==> demo: [INFO] ------------------------------------------------------------------------
==> demo: Downloading: https://bits.lumify.io/nexus/content/repositories/releases/com/altamiracorp/bigtable/bigtable-jetty-session-manager/0.5.0/bigtable-jetty-session-manager-0.5.0.pom
==> demo: 3/3 KB
==> demo:
==> demo: Downloading: http://gwtwiki.googlecode.com/svn/maven-repository/com/altamiracorp/bigtable/bigtable-jetty-session-manager/0.5.0/bigtable-jetty-session-manager-0.5.0.pom
==> demo: Nov 02, 2015 6:48:09 PM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
==> demo: INFO: I/O exception (java.net.SocketException) caught when processing request to {}->http://gwtwiki.googlecode.com:80: Network is unreachable
==> demo: Nov 02, 2015 6:48:09 PM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
==> demo: INFO: Retrying request to {}->http://gwtwiki.googlecode.com:80
==> demo: Nov 02, 2015 6:48:10 PM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
==> demo: INFO: I/O exception (java.net.SocketException) caught when processing request to {}->http://gwtwiki.googlecode.com:80: Network is unreachable
==> demo: Nov 02, 2015 6:48:10 PM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
==> demo: INFO: Retrying request to {}->http://gwtwiki.googlecode.com:80
==> demo:
==> demo: Downloading: https://repo.maven.apache.org/maven2/com/altamiracorp/bigtable/bigtable-jetty-session-manager/0.5.0/bigtable-jetty-session-manager-0.5.0.pom
==> demo:
==> demo: Downloading: http://artifactory.altamiracorp.com/artifactory/libs-release-local/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.pom
==> demo:
==> demo: Downloading: https://bits.lumify.io/nexus/content/repositories/releases/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.pom
==> demo:
==> demo: Downloading: https://bits.lumify.io/nexus/content/repositories/snapshots/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.pom
==> demo:
==> demo: Downloading: http://oss.sonatype.org/content/repositories/snapshots/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.pom
==> demo: Nov 02, 2015 6:48:17 PM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
==> demo: INFO: I/O exception (java.net.SocketException) caught when processing request to {}->http://oss.sonatype.org:80: Network is unreachable
==> demo: Nov 02, 2015 6:48:17 PM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
==> demo: INFO: Retrying request to {}->http://oss.sonatype.org:80
==> demo: Nov 02, 2015 6:48:17 PM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
==> demo: INFO: I/O exception (java.net.SocketException) caught when processing request to {}->http://oss.sonatype.org:80: Network is unreachable
==> demo: Nov 02, 2015 6:48:17 PM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
==> demo: INFO: Retrying request to {}->http://oss.sonatype.org:80
==> demo: Nov 02, 2015 6:48:17 PM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
==> demo: INFO: I/O exception (java.net.SocketException) caught when processing request to {}->http://oss.sonatype.org:80: Network is unreachable
==> demo: Nov 02, 2015 6:48:17 PM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
==> demo: INFO: Retrying request to {}->http://oss.sonatype.org:80
==> demo:
==> demo: [WARNING] Failed to write tracking file /home/vagrant/.m2/repository/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.pom.lastUpdated
==> demo: java.io.IOException: Too many open files in system
==> demo:       at java.io.RandomAccessFile.setLength(Native Method)
==> demo:       at org.eclipse.aether.internal.impl.TrackingFileManager.update(TrackingFileManager.java:130)
```

_Note: this is only the first instance; the build errors cascade from here_

Suspecting that the main cause is `java.io.IOException: Too many open files in system`, I checked the max open files, and found that they are low (hard limit 4096).

On CentOS, the following will increase the limit

```
echo "fs.file-max = 200500" | sudo tee -a /etc/sysctl.conf
echo "vagrant soft nofile 4096" | sudo tee -a /etc/security/limits.conf
echo "vagrant hard nofile 10240" | sudo tee /etc/security/limits.conf
sudo sysctl -p
```

Followed by logging out of the shell session.

I've attempted to resolve it locally to do a PR, but cannot progress with this issue.

**Comment by Joshfindit** [comment]
Pending investigation; closing this due to potential issues with the host.
