### ISSUE TITLE
EntityHighlighterTest - multiple failures

### ISSUE THREAD

**Issue by jonyt** [lumifyio/lumify#675]
Running `mvn -X -e package -pl tools/cli/ -am` I get the errors below. It's really only a matter of the ordering of the properties.

```
Running io.lumify.core.EntityHighlighterTest
Tests run: 3, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.14 sec <<< FAILURE! - in io.lumify.core.EntityHighlighterTest
testGetHighlightedText(io.lumify.core.EntityHighlighterTest)  Time elapsed: 0.111 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<...terTest&quot;,&quot;[id&quot;:&quot;TM_--18-28-EntityHighlighterTest&quot;,&quot;title&quot;:&quot;joe ferner&quot;,&quot;sandboxStatus&quot;:&quot;PRIVATE&quot;,&quot;http://lumify.io#conceptType&quot;:&quot;http://lumify.io/test/person&quot;,&quot;start&quot;:18,&quot;sourceVertexId&quot;:&quot;1&quot;,&quot;type&quot;:&quot;http://www.w3.org/2002/07/owl#Thing&quot;,&quot;end&quot;:28}">Joe Ferner</span> and <span class="vertex" title="jeff kunkle" data-info="{&quot;process&quot;:&quot;uniq1&quot;,&quot;id&quot;:&quot;TM_--33-44-uniq1&quot;,&quot;title&quot;:&quot;jeff kunkle&quot;,&quot;sandboxStatus&quot;:&quot;PRIVATE&quot;,&quot;http://lumify.io#conceptType&quot;:&quot;http://lumify.io/test/person&quot;,&quot;start&quot;:33,&quot;sourceVertexId&quot;:&quot;1&quot;,&quot;type&quot;:&quot;http://www.w3.org/2002/07/owl#Thing&quot;,&quot;end&quot;:44]}">Jeff Kunkle</span...> but was:<...terTest&quot;,&quot;[start&quot;:18,&quot;end&quot;:28,&quot;id&quot;:&quot;TM_--18-28-EntityHighlighterTest&quot;,&quot;type&quot;:&quot;http://www.w3.org/2002/07/owl#Thing&quot;,&quot;title&quot;:&quot;joe ferner&quot;,&quot;sandboxStatus&quot;:&quot;PRIVATE&quot;,&quot;http://lumify.io#conceptType&quot;:&quot;http://lumify.io/test/person&quot;,&quot;sourceVertexId&quot;:&quot;1&quot;}">Joe Ferner</span> and <span class="vertex" title="jeff kunkle" data-info="{&quot;process&quot;:&quot;uniq1&quot;,&quot;start&quot;:33,&quot;end&quot;:44,&quot;id&quot;:&quot;TM_--33-44-uniq1&quot;,&quot;type&quot;:&quot;http://www.w3.org/2002/07/owl#Thing&quot;,&quot;title&quot;:&quot;jeff kunkle&quot;,&quot;sandboxStatus&quot;:&quot;PRIVATE&quot;,&quot;http://lumify.io#conceptType&quot;:&quot;http://lumify.io/test/person&quot;,&quot;sourceVertexId&quot;:&quot;1&quot;]}">Jeff Kunkle</span...>
    at org.junit.Assert.assertEquals(Assert.java:115)
    at org.junit.Assert.assertEquals(Assert.java:144)
    at io.lumify.core.EntityHighlighterTest.testGetHighlightedText(EntityHighlighterTest.java:62)

testGetHighlightedTextWithAccentedCharacters(io.lumify.core.EntityHighlighterTest)  Time elapsed: 0.001 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<...terTest&quot;,&quot;[id&quot;:&quot;TM_--48-50-EntityHighlighterTest&quot;,&quot;title&quot;:&quot;US&quot;,&quot;sandboxStatus&quot;:&quot;PRIVATE&quot;,&quot;http://lumify.io#conceptType&quot;:&quot;http://lumify.io/test/location&quot;,&quot;start&quot;:48,&quot;sourceVertexId&quot;:&quot;1&quot;,&quot;type&quot;:&quot;http://www.w3.org/2002/07/owl#Thing&quot;,&quot;end&quot;:50]}">US</span> on peac...> but was:<...terTest&quot;,&quot;[start&quot;:48,&quot;end&quot;:50,&quot;id&quot;:&quot;TM_--48-50-EntityHighlighterTest&quot;,&quot;type&quot;:&quot;http://www.w3.org/2002/07/owl#Thing&quot;,&quot;title&quot;:&quot;US&quot;,&quot;sandboxStatus&quot;:&quot;PRIVATE&quot;,&quot;http://lumify.io#conceptType&quot;:&quot;http://lumify.io/test/location&quot;,&quot;sourceVertexId&quot;:&quot;1&quot;]}">US</span> on peac...>
    at org.junit.Assert.assertEquals(Assert.java:115)
    at org.junit.Assert.assertEquals(Assert.java:144)
    at io.lumify.core.EntityHighlighterTest.testGetHighlightedTextWithAccentedCharacters(EntityHighlighterTest.java:166)


Results :

Failed tests: 
  EntityHighlighterTest.testGetHighlightedText:62 expected:<...terTest&quot;,&quot;[id&quot;:&quot;TM_--18-28-EntityHighlighterTest&quot;,&quot;title&quot;:&quot;joe ferner&quot;,&quot;sandboxStatus&quot;:&quot;PRIVATE&quot;,&quot;http://lumify.io#conceptType&quot;:&quot;http://lumify.io/test/person&quot;,&quot;start&quot;:18,&quot;sourceVertexId&quot;:&quot;1&quot;,&quot;type&quot;:&quot;http://www.w3.org/2002/07/owl#Thing&quot;,&quot;end&quot;:28}">Joe Ferner</span> and <span class="vertex" title="jeff kunkle" data-info="{&quot;process&quot;:&quot;uniq1&quot;,&quot;id&quot;:&quot;TM_--33-44-uniq1&quot;,&quot;title&quot;:&quot;jeff kunkle&quot;,&quot;sandboxStatus&quot;:&quot;PRIVATE&quot;,&quot;http://lumify.io#conceptType&quot;:&quot;http://lumify.io/test/person&quot;,&quot;start&quot;:33,&quot;sourceVertexId&quot;:&quot;1&quot;,&quot;type&quot;:&quot;http://www.w3.org/2002/07/owl#Thing&quot;,&quot;end&quot;:44]}">Jeff Kunkle</span...> but was:<...terTest&quot;,&quot;[start&quot;:18,&quot;end&quot;:28,&quot;id&quot;:&quot;TM_--18-28-EntityHighlighterTest&quot;,&quot;type&quot;:&quot;http://www.w3.org/2002/07/owl#Thing&quot;,&quot;title&quot;:&quot;joe ferner&quot;,&quot;sandboxStatus&quot;:&quot;PRIVATE&quot;,&quot;http://lumify.io#conceptType&quot;:&quot;http://lumify.io/test/person&quot;,&quot;sourceVertexId&quot;:&quot;1&quot;}">Joe Ferner</span> and <span class="vertex" title="jeff kunkle" data-info="{&quot;process&quot;:&quot;uniq1&quot;,&quot;start&quot;:33,&quot;end&quot;:44,&quot;id&quot;:&quot;TM_--33-44-uniq1&quot;,&quot;type&quot;:&quot;http://www.w3.org/2002/07/owl#Thing&quot;,&quot;title&quot;:&quot;jeff kunkle&quot;,&quot;sandboxStatus&quot;:&quot;PRIVATE&quot;,&quot;http://lumify.io#conceptType&quot;:&quot;http://lumify.io/test/person&quot;,&quot;sourceVertexId&quot;:&quot;1&quot;]}">Jeff Kunkle</span...>
  EntityHighlighterTest.testGetHighlightedTextWithAccentedCharacters:166 expected:<...terTest&quot;,&quot;[id&quot;:&quot;TM_--48-50-EntityHighlighterTest&quot;,&quot;title&quot;:&quot;US&quot;,&quot;sandboxStatus&quot;:&quot;PRIVATE&quot;,&quot;http://lumify.io#conceptType&quot;:&quot;http://lumify.io/test/location&quot;,&quot;start&quot;:48,&quot;sourceVertexId&quot;:&quot;1&quot;,&quot;type&quot;:&quot;http://www.w3.org/2002/07/owl#Thing&quot;,&quot;end&quot;:50]}">US</span> on peac...> but was:<...terTest&quot;,&quot;[start&quot;:48,&quot;end&quot;:50,&quot;id&quot;:&quot;TM_--48-50-EntityHighlighterTest&quot;,&quot;type&quot;:&quot;http://www.w3.org/2002/07/owl#Thing&quot;,&quot;title&quot;:&quot;US&quot;,&quot;sandboxStatus&quot;:&quot;PRIVATE&quot;,&quot;http://lumify.io#conceptType&quot;:&quot;http://lumify.io/test/location&quot;,&quot;sourceVertexId&quot;:&quot;1&quot;]}">US</span> on peac...>

Tests run: 31, Failures: 2, Errors: 0, Skipped: 0
```

**Comment by aru1992** [comment]
I am also getting this error


**Running io.lumify.core.EntityHighlighterTest**
WARN   getVertex, Performing scan of all vertices! Override getVertex.
WARN   getVertex, Performing scan of all vertices! Override getVertex.
WARN   getEdge, Performing scan of all edges! Override getEdge.
WARN   getVertex, Performing scan of all vertices! Override getVertex.
WARN   getEdge, Performing scan of all edges! Override getEdge.
WARN   getVertex, Performing scan of all vertices! Override getVertex.
WARN   getVertex, Performing scan of all vertices! Override getVertex.
WARN   getEdge, Performing scan of all edges! Override getEdge.
Tests run: 3, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 1.357 sec <<< FAILURE! - in **io.lumify.core.EntityHighlighterTest
testGetHighlightedText(io.lumify.core.EntityHighlighterTest)  Time elapsed: 0.429 sec  <<< ERROR!
java.lang.ExceptionInInitializerError: null**
	at io.lumify.core.config.FileConfigurationLoader.resolveFileName(FileConfigurationLoader.java:152)
	at io.lumify.core.config.ConfigurationLoader.doConfigureLog4j(ConfigurationLoader.java:100)
	at io.lumify.core.config.ConfigurationLoader.configureLog4j(ConfigurationLoader.java:24)
	at io.lumify.core.util.LumifyLoggerFactory.ensureInitialized(LumifyLoggerFactory.java:26)
	at io.lumify.core.util.LumifyLoggerFactory.getLogger(LumifyLoggerFactory.java:15)
	at io.lumify.core.util.GraphUtil.<clinit>(GraphUtil.java:24)
	at io.lumify.core.EntityHighlighter.convertTermMentionsToOffsetItems(EntityHighlighter.java:166)
	at io.lumify.core.EntityHighlighterTest.testGetHighlightedText(EntityHighlighterTest.java:60)

testGetHighlightedTextWithAccentedCharacters(io.lumify.core.EntityHighlighterTest)  Time elapsed: 0.002 sec  <<< ERROR!
**java.lang.NoClassDefFoundError: Could not initialize class io.lumify.core.util.GraphUtil
	at io.lumify.core.EntityHighlighter.convertTermMentionsToOffsetItems(EntityHighlighter.java:166)
	at io.lumify.core.EntityHighlighterTest.testGetHighlightedTextWithAccentedCharacters(EntityHighlighterTest.java:164)**

Running io.lumify.core.model.ontology.PropertyTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in io.lumify.core.model.ontology.PropertyTest
Running io.lumify.core.model.ValueTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.095 sec - in io.lumify.core.model.ValueTest
Running io.lumify.core.config.ConfigurationTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.026 sec - in io.lumify.core.config.ConfigurationTest
Running io.lumify.core.formula.FormulaEvaluatorTest
FormulaEvaluatorTest-testThreading-0 - 0
FormulaEvaluatorTest-testThreading-0 - 1
FormulaEvaluatorTest-testThreading-0 - 2
FormulaEvaluatorTest-testThreading-3 - 0
FormulaEvaluatorTest-testThreading-3 - 1
FormulaEvaluatorTest-testThreading-3 - 2
FormulaEvaluatorTest-testThreading-2 - 0
FormulaEvaluatorTest-testThreading-2 - 1
FormulaEvaluatorTest-testThreading-2 - 2
FormulaEvaluatorTest-testThreading-2 - 3
FormulaEvaluatorTest-testThreading-2 - 4
FormulaEvaluatorTest-testThreading-2 - 5
FormulaEvaluatorTest-testThreading-3 - 3
FormulaEvaluatorTest-testThreading-3 - 4
FormulaEvaluatorTest-testThreading-3 - 5
FormulaEvaluatorTest-testThreading-1 - 0
FormulaEvaluatorTest-testThreading-0 - 3
FormulaEvaluatorTest-testThreading-0 - 4
FormulaEvaluatorTest-testThreading-0 - 5
FormulaEvaluatorTest-testThreading-1 - 1
FormulaEvaluatorTest-testThreading-1 - 2
FormulaEvaluatorTest-testThreading-1 - 3
FormulaEvaluatorTest-testThreading-2 - 6
FormulaEvaluatorTest-testThreading-2 - 7
FormulaEvaluatorTest-testThreading-2 - 8
FormulaEvaluatorTest-testThreading-0 - 6
FormulaEvaluatorTest-testThreading-0 - 7
FormulaEvaluatorTest-testThreading-3 - 6
FormulaEvaluatorTest-testThreading-3 - 7
FormulaEvaluatorTest-testThreading-3 - 8
FormulaEvaluatorTest-testThreading-3 - 9
FormulaEvaluatorTest-testThreading-3 - 10
FormulaEvaluatorTest-testThreading-1 - 4
FormulaEvaluatorTest-testThreading-1 - 5
FormulaEvaluatorTest-testThreading-1 - 6
FormulaEvaluatorTest-testThreading-0 - 8
FormulaEvaluatorTest-testThreading-0 - 9
FormulaEvaluatorTest-testThreading-0 - 10
FormulaEvaluatorTest-testThreading-0 - 11
FormulaEvaluatorTest-testThreading-0 - 12
FormulaEvaluatorTest-testThreading-3 - 11
FormulaEvaluatorTest-testThreading-2 - 9
FormulaEvaluatorTest-testThreading-2 - 10
FormulaEvaluatorTest-testThreading-2 - 11
FormulaEvaluatorTest-testThreading-2 - 12
FormulaEvaluatorTest-testThreading-1 - 7
FormulaEvaluatorTest-testThreading-1 - 8
FormulaEvaluatorTest-testThreading-1 - 9
FormulaEvaluatorTest-testThreading-3 - 12
FormulaEvaluatorTest-testThreading-3 - 13
FormulaEvaluatorTest-testThreading-3 - 14
FormulaEvaluatorTest-testThreading-3 - 15
FormulaEvaluatorTest-testThreading-0 - 13
FormulaEvaluatorTest-testThreading-0 - 14
FormulaEvaluatorTest-testThreading-0 - 15
FormulaEvaluatorTest-testThreading-2 - 13
FormulaEvaluatorTest-testThreading-2 - 14
FormulaEvaluatorTest-testThreading-2 - 15
FormulaEvaluatorTest-testThreading-2 - 16
FormulaEvaluatorTest-testThreading-2 - 17
FormulaEvaluatorTest-testThreading-3 - 16
FormulaEvaluatorTest-testThreading-1 - 10
FormulaEvaluatorTest-testThreading-0 - 16
FormulaEvaluatorTest-testThreading-1 - 11
FormulaEvaluatorTest-testThreading-1 - 12
FormulaEvaluatorTest-testThreading-1 - 13
FormulaEvaluatorTest-testThreading-1 - 14
FormulaEvaluatorTest-testThreading-0 - 17
FormulaEvaluatorTest-testThreading-0 - 18
FormulaEvaluatorTest-testThreading-3 - 17
FormulaEvaluatorTest-testThreading-3 - 18
FormulaEvaluatorTest-testThreading-3 - 19
FormulaEvaluatorTest-testThreading-1 - 15
FormulaEvaluatorTest-testThreading-1 - 16
FormulaEvaluatorTest-testThreading-2 - 18
FormulaEvaluatorTest-testThreading-2 - 19
FormulaEvaluatorTest-testThreading-2 - closing evaluator
FormulaEvaluatorTest-testThreading-0 - 19
FormulaEvaluatorTest-testThreading-0 - closing evaluator
FormulaEvaluatorTest-testThreading-0 - evaluator closed
FormulaEvaluatorTest-testThreading-3 - closing evaluator
FormulaEvaluatorTest-testThreading-3 - evaluator closed
FormulaEvaluatorTest-testThreading-1 - 17
FormulaEvaluatorTest-testThreading-2 - evaluator closed
FormulaEvaluatorTest-testThreading-1 - 18
FormulaEvaluatorTest-testThreading-1 - 19
FormulaEvaluatorTest-testThreading-1 - closing evaluator
FormulaEvaluatorTest-testThreading-1 - evaluator closed
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 17.217 sec - in io.lumify.core.formula.FormulaEvaluatorTest
Running io.lumify.core.util.FixedSizeCircularLinkedListTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.006 sec - in io.lumify.core.util.FixedSizeCircularLinkedListTest
Running io.lumify.core.util.TeeInputStreamTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.713 sec - in io.lumify.core.util.TeeInputStreamTest
Running io.lumify.core.util.AutoDependencyTreeRunnerTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.018 sec - in io.lumify.core.util.AutoDependencyTreeRunnerTest
Running io.lumify.core.util.ThreadedInputStreamProcessTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.832 sec - in io.lumify.core.util.ThreadedInputStreamProcessTest
Running io.lumify.core.util.HdfsLimitOutputStreamTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.225 sec - in io.lumify.core.util.HdfsLimitOutputStreamTest
Running io.lumify.core.util.IsClosedInputStreamTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec - in io.lumify.core.util.IsClosedInputStreamTest
Running io.lumify.core.version.VersionServiceTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.01 sec - in io.lumify.core.version.VersionServiceTest

Results :

Tests in error: 
  EntityHighlighterTest.testGetHighlightedText:60 » ExceptionInInitializer
  EntityHighlighterTest.testGetHighlightedTextWithAccentedCharacters:164 » NoClassDefFound

Tests run: 31, Failures: 0, Errors: 2, Skipped: 0

please tell me how can I resolve this.....
